version: '3.8'  
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin@123
      RABBITMQ_VIRTUAL_HOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
